# Generated by Django 3.1.2 on 2021-03-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchEngine',
            new_name='SearchData',
        ),
    ]
