# Generated by Django 3.1.2 on 2021-03-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchengine', '0003_auto_20210302_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchinput',
            old_name='job_title',
            new_name='job_search',
        ),
        migrations.RenameField(
            model_name='searchinput',
            old_name='job_location',
            new_name='location_search',
        ),
    ]
